### ISSUE TITLE
Todo at Client

### ISSUE THREAD

**Issue by powerfulyang** [powerfulyang/powerfulyang.com#32]
- [x] Unit Test example
- [x] timeline background image url is not refreshed
- [x] ~~websocket with [next-pwa](https://github.com/shadowwalker/next-pwa) didn't work fine~~

**Comment by powerfulyang** [comment]
- [ ] 从非等宽字体 swap to 等宽字体页面闪烁，不知道能不能解决呢。

**Comment by powerfulyang** [comment]
- [ ] https://github.com/peers/peerjs/issues/630#issuecomment-1046151278
- [ ] https://github.com/vercel/next.js/issues/35835#issuecomment-1100057011
- [ ] https://github.com/vercel/next.js/issues/36127#issuecomment-1112240572
